project:
    type: book

book:
    title: "Foundations of Computer Vision"
    repo-url: https://github.com/shensquared/cv_book
    repo-actions: [edit, issue, source]
    repo-subdir: /
    author: "Antonio Torralba, Phillip Isola, and William Freeman"
    date: "04/16/2024"
    chapters:
        - index.qmd
        - notations.qmd
        - taxonomy.qmd
        - part: Foundations
          chapters:
              - simplesystem.qmd
              - visionscience.qmd
              - fairness.qmd
        - part: Image Formation
          chapters:
              - imaging.qmd
              - lenses.qmd
              - camera_as_linsys.qmd
              - color.qmd
        - part: Foundations of Learning
          chapters:
              - intro_to_learning.qmd
              #   - gradient_descent.qmd
              - problem_of_generalization.qmd
              #   - neural_nets.qmd
              #   - neural_nets_as_distribution_transformers.qmd
              #   - backpropagation.qmd

        - references.qmd
    # favicon: Figures/favicon.ico
    cover-image: figures/logo.jpg
    downloads: [pdf]
    sharing: [twitter]
    sidebar:
        style: "floating"
        collapse-level: 2
        border: true
        search: true
    page-footer:
        left: "All content licensed under [CC BY-NC-SA 4.01](https://creativecommons.org/licenses/by-nc-sa/)<br> Antonio Torralba, Phillip Isola, and William Freeman"
        center: "[Website](https://shenshen.mit.edu/cv_book) | [GitHub](https://github.com/shensquared/cv_book) | [MIT Vision Group](http://groups.csail.mit.edu/vision)"
        right: Built with [Quarto](https://quarto.org/).

bibliography:
    - src/all.bib
    - src/visionbib.bib

format:
    html:
        fontsize: "16px"
        linestretch: 1.6
        mainfont: "Palatino"
        monofont: "Fira Mono"
        smooth-scroll: true
        toc-depth: 3
        code-link: false
        code-tools:
            toggle: false
        code-fold: false
        highlight-style: printing
        code-block-bg: true
        code-overflow: wrap
        reference-location: margin
        cap-location: margin
        css: ./scripts/custom-style.css
        theme: cosmo
        mathjax: true
        # mermaid:
        # theme: neutral

    # see https://pandoc.org/MANUAL.html for all options
#     pdf:
#         documentclass: src/DL_class
#         classoption: DL_class
#         lof: false
#         lot: false
#         toc: false
#         toc-depth: 2
#         fig-cap-location: bottom
#         tbl-cap-location: top
#         urlcolor: "blue"
#         linkcolor: "black"
#         biblio-style: apalike
#         keep-tex: true
#         code-block-bg: "#f2f2f2"
#         code-block-border-left: "#f2f2f2"
#         code-overflow: wrap
#         mermaid:
#             theme: neutral
#         include-in-header:
#             - src/setup.tex
#             - text: |
#                   \usepackage{makeidx}
#                   \makeindex
#         include-after-body:
#             text: |
#                 \printindex
# # https://christophertkenny.com/posts/2023-07-01-creating-quarto-journal-articles/
# latex-auto-install: true
comments:
    hypothesis: true
