name: Quarto Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Quarto
        run: |
          wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.5.56/quarto-1.5.56-linux-arm64.deb
          sudo dpkg -i quarto-1.5.56-linux-arm64.deb
          
      - name: Render Quarto Project
        run: |
          quarto render

      # - name: Deploy to remote
      # run: |
